<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Project_model extends CI_Model
{

    public $table = 'mitra_project';
    public $id = 'project_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('project_id,project_mitra_id,project_kode,project_nama,project_detail,project_nilai,project_lampiran,project_aktifasi,project_create_date,project_create_by,project_update_date,project_update_by');
        $this->datatables->from('mitra_project');
        //add this line for join
        //$this->datatables->join('table2', 'mitra_project.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('project/read/$1'),'Read')." | ".anchor(site_url('project/update/$1'),'Update')." | ".anchor(site_url('project/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'project_id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('project_id', $q);
	$this->db->or_like('project_mitra_id', $q);
	$this->db->or_like('project_kode', $q);
	$this->db->or_like('project_nama', $q);
	$this->db->or_like('project_detail', $q);
	$this->db->or_like('project_nilai', $q);
	$this->db->or_like('project_lampiran', $q);
	$this->db->or_like('project_aktifasi', $q);
	$this->db->or_like('project_create_date', $q);
	$this->db->or_like('project_create_by', $q);
	$this->db->or_like('project_update_date', $q);
	$this->db->or_like('project_update_by', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('project_id', $q);
	$this->db->or_like('project_mitra_id', $q);
	$this->db->or_like('project_kode', $q);
	$this->db->or_like('project_nama', $q);
	$this->db->or_like('project_detail', $q);
	$this->db->or_like('project_nilai', $q);
	$this->db->or_like('project_lampiran', $q);
	$this->db->or_like('project_aktifasi', $q);
	$this->db->or_like('project_create_date', $q);
	$this->db->or_like('project_create_by', $q);
	$this->db->or_like('project_update_date', $q);
	$this->db->or_like('project_update_by', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Project_model.php */
/* Location: ./application/models/Project_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-09-20 11:43:44 */
/* http://harviacode.com */