<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Project extends Admin_Controller
{
    function __construct()
    {
        parent::__construct();        
                $files = array(
                            'app-assets/vendors/js/forms/spinner/jquery.bootstrap-touchspin.js',                
                            'app-assets/vendors/js/forms/validation/jqBootstrapValidation.js',
                            'app-assets/vendors/js/forms/toggle/bootstrap-switch.min.js',
                            'app-assets/js/scripts/forms/validation/form-validation.js',
                            'app-assets/js/scripts/pages/project-bug-list.js',
                            'app-assets/vendors/js/forms/select/select2.min.js',
                            'app-assets/vendors/js/tables/jquery.dataTables.min.js',
                            'app-assets/vendors/js/tables/datatable/dataTables.bootstrap4.min.js',
                            'assets/custom_theme/custom.js',
                );
                $screen = array(
                            'app-assets/css/plugins/forms/validation/form-validation.css',
                            'app-assets/vendors/css/tables/datatable/dataTables.bootstrap4.min.css',
                            'app-assets/vendors/css/tables/extensions/rowReorder.dataTables.min.css',
                            'app-assets/vendors/css/tables/extensions/responsive.dataTables.min.css',
                            'app-assets/vendors/css/forms/icheck/icheck.css',
                            'app-assets/vendors/css/forms/icheck/custom.css',
                            'app-assets/vendors/css/ui/jquery-ui.min.css',
                            'app-assets/vendors/css/forms/selects/select2.min.css',
                );
//                $this->add_script($files);  
//                $this->add_stylesheet($screen);
    }

    public function index()
    {
        $this->render('project/project_list');
    } 
    public function Create() {
        $this->render('project/project_create');
    }
}

/* End of file Project.php */
/* Location: ./application/controllers/Project.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-09-20 11:43:43 */
/* http://harviacode.com */